VD
T* VD< T >::datos
zona de memoria del array
int VD< T >::reservados
espacio reservado en datos
int VD< T >::n
elementos almacenados
void VD< T >::resize(int tam)
Cambio del tamaño del vector dinamico.
tam tamaño del vector dinamico Crea el VD de con espacio reservado de tamaño tam
void VD< T >::copiar(const VD< T > &v)
copias de la clase
v.reservados espacio reservado en datos a construir v.n lementos almacenados a construir
void VD< T >::liberar()
liberar la clase, eliminando los elementos
VD< T >::VD(int tam=1)
Constructor de la clase.
tam tamaño del vector dinamico Crea el VD de con espacio reservado de tamaño mayor que 1
VD< T >::VD(const VD< T > &v)
Constructor de copias de la clase.
v.reservados espacio reservado en datos a construir v.n lementos almacenados a construir
VD< T > & VD< T >::operator=(const VD< T > &v)
Asignacion de dos vector dinamico.
v vector a asignar con el objeto implicito
VD< T >::~VD()
Destructor de la clase.
int VD< T >::size() const
Devolver el elemento almacenados n.
Referenced by Palabras::getDiferentTipos.
T & VD< T >::operator[](int i)
Devuelve una referencoa al objeto i-th en el vactor.
i indice del elemento a devolver una referencia al objeto i-th i>=0 y i<n
const T & VD< T >::operator[](int i) const
void VD< T >::insert(int pos, const T &d)
Insertar un nuevo elemento en una posicion dada.
pos posicion donde se inserta el elemento d elemento a insertar que la posicion debe estar entre 0 y n
Referenced by Palabras::getDiferentTipos, Palabras::getTipoPalabra.
void VD< T >::erase(int pos)
Eliminar un elemento en una posicion dada.
pos posicion donde se elimina el elemento que la posicion debe estar entre 0 y n
void VD< T >::clear()
Inicializa el elementos almacenados a 0.