.TH "include/palabra.h" 3 "Domingo, 7 de Noviembre de 2021" "Práctica 2: Palabras y Sinónimos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/palabra.h
.SH SYNOPSIS
.br
.PP
\fC#include <cassert>\fP
.br
\fC#include <string>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'vd\&.h'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBPalabra\fP"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Práctica 2: Palabras y Sinónimos del código fuente\&.
