.TH "include/vd.h" 3 "Domingo, 7 de Noviembre de 2021" "Práctica 2: Palabras y Sinónimos" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/vd.h \- Fichero cabecera del TDA Vector Dinamico\&.  

.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./src/vd\&.cpp'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBVD< T >\fP"
.br
.RI "T\&.D\&.A\&. \fBVD\fP\&. "
.in -1c
.SH "Descripción detallada"
.PP 
Fichero cabecera del TDA Vector Dinamico\&. 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Práctica 2: Palabras y Sinónimos del código fuente\&.
